name: code-check

on:
  push:

jobs:
  build:
    name: ğŸ‘·ğŸ»â€â™€ï¸ Build
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ§° Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: ğŸ› ï¸ Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: ğŸ§³ Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ§½ Prettier
        run: pnpm run format:check

      - name: ğŸ‘®ğŸ» Lint
        run: pnpm run lint
